### ISSUE TITLE
[Security] Workflow build-ci.yml is using vulnerable action ilammy/msvc-dev-cmd

### ISSUE THREAD

**Issue by qazaqstan2025** [adxeproject/buildware#2]
The workflow build-ci.yml is referencing action ilammy/msvc-dev-cmd using references v1.9.0. However this reference is missing the commit [74a501b08777cf58d13c44adae25530a78e3120e](https://github.com/ilammy/msvc-dev-cmd/commits/74a501b08777cf58d13c44adae25530a78e3120e) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by halx99** [comment]
Thanks, will update soon

**Comment by halx99** [comment]
Released: https://github.com/adxeproject/buildware/releases/tag/1.2.4
