### ISSUE TITLE
Locate Visual Studio

### ISSUE THREAD

**Issue by martinking71** [adxeproject/buildware#24]
I just have the vs build tools installed not a full vs studio install so the find_vs() function fails to find vs_studio() when trying to set up the axmol game framework

If I modify the function by adding the -all -products Microsoft.VisualStudio.Product.BuildTools option to the command, it finds my build tools.

The axmol setup script then runs fine and I can then edit and build my projects.

Not sure if this belongs in here or in the axmol project.

**Comment by halx99** [comment]
Yes, belong to there and sync to axmol
